const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null?'—':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(v);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let S={products:[],jobs:[],sales:[],settings:{},capabilities:{}},view='research',selected=new Set(),search='',studioId='',assetTab='all',chartType='bar',filters={platform:'',start:'',end:''};
const sellers=['Amazon','TikTok Shop','AliExpress'],platforms=[...sellers,'Zooplus','Arcaplanet'];
const navs=[['research','⌕','数据调研'],['schedule','▦','选品排期'],['studio','▧','AI 创作工坊'],['uploads','☑','上架清单'],['analytics','▥','经营分析'],['settings','⚙','连接与设置']];
const product=id=>S.products.find(p=>p.id===id);
const safeUrl=v=>{try{const u=new URL(v,location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').style.display='none',4200)}
async function api(path,data){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'操作失败');return j}
async function act(path,data,msg='已保存'){try{const r=await api(path,data);await refresh();toast(msg);return r}catch(e){toast(e.message);return null}}
async function refresh(redraw=true){try{const r=await fetch('/api/state');if(!r.ok)throw Error('无法连接本地服务');S=await r.json();if(redraw)render()}catch(e){toast(e.message)}}
function go(v){view=v;search='';render();location.hash=v}
function render(){$('#nav').innerHTML=navs.map(([v,i,t],n)=>`<button class="${v===view?'active':''}" onclick="go('${v}')"><em>${i}</em>${t}${n<5?`<span>0${n+1}</span>`:''}</button>`).join('');$('#crumb').textContent=navs.find(n=>n[0]===view)[2];$('#app').innerHTML=({research,schedule,studio,uploads,analytics,settings}[view])()}
function head(kicker,title,desc,actions=''){return `<div class="page-top"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`}
function stat(label,val,note){return `<div class="stat"><label>${label}</label><strong>${val}</strong><small>${note}</small></div>`}
function empty(title,desc,action=''){return `<div class="empty"><div class="empty-icon">◇</div><strong>${title}</strong><p>${desc}</p>${action}</div>`}
function tag(t,cls=''){return `<span class="tag ${cls}">${esc(t)}</span>`}
function img(p,large=false){const src=p.reference?'/files/'+p.reference:safeUrl(p.cover);return src?`<img class="thumb ${large?'large':''}" src="${esc(src)}" alt="${esc(p.nameZh||p.sku)}" referrerpolicy="no-referrer" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'thumb',textContent:'图片失效'}))">`:`<span class="thumb ${large?'large':''}">待上传</span>`}
function productCell(p){return `<div class="product-cell">${img(p)}<div><strong>${esc(p.nameZh||p.nameIt||p.sku)}</strong><p>${esc(p.nameIt||'意大利语名称待补充')}</p><p class="mono">${esc(p.sku)}</p></div></div>`}
function field(name,label,val='',type='text',extra=''){return `<div class="field"><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(val??'')}" ${extra}></div>`}
function textfield(name,label,val='',extra=''){return `<div class="field ${extra}"><label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}">${esc(val||'')}</textarea></div>`}
function selectfield(name,label,options,value=''){return `<div class="field"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}">${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`}).join('')}</select></div>`}
function modal(title,body){$('#dialog').innerHTML=`<div class="page-top"><h1>${title}</h1><button type="button" aria-label="关闭" onclick="$('#dialog').close()">×</button></div>${body}`;if(!$('#dialog').open)$('#dialog').showModal()}
function finishButtons(label='保存'){return `<div class="actions full" style="justify-content:flex-end;margin-top:10px"><button type="button" onclick="$('#dialog').close()">取消</button><button class="primary" type="submit">${label}</button></div>`}
async function submitForm(event,fn){event.preventDefault();const btn=event.target.querySelector('button[type=submit]');btn.disabled=true;try{await fn(Object.fromEntries(new FormData(event.target)))}catch(e){toast(e.message)}finally{btn.disabled=false}}
const filteredProducts=()=>S.products.filter(p=>[p.sku,p.nameZh,p.nameIt,p.ean].join(' ').toLowerCase().includes(search.toLowerCase()));
function selectOne(id,checked){checked?selected.add(id):selected.delete(id);const el=$('#selection-count');if(el)el.textContent=selected.size}
function selectAll(checked){filteredProducts().forEach(p=>checked?selected.add(p.id):selected.delete(p.id));render()}
function research(){return head('DISCOVER YOUR NEXT BESTSELLER','数据调研','从一个 SKU 开始，找到适合意大利市场的好产品。',`<button onclick="importDialog('products')">导入商品</button><button class="primary" onclick="editProduct()">＋ 添加 SKU</button>`)+`<div class="stats">${stat('仓库商品',S.products.length,'建立统一的商品档案')}${stat('已获得报价',S.products.filter(p=>p.offers.some(o=>o.price!=null)).length,'五个平台 · 来源可追溯')}${stat('已选品',S.products.filter(p=>p.selected).length,'进入排期，逐步测试')}${stat('待补充成本',S.products.filter(p=>p.cost==null).length,'补齐后自动计算目标售价')}</div><div class="card"><div class="card-head"><h2>商品调研库 <span class="pill-number">${S.products.length}</span></h2>${tag('意大利 · B2C','green')}</div><div class="toolbar"><input class="search" aria-label="搜索商品" value="${esc(search)}" placeholder="搜索 SKU、中文或意大利语名称" oninput="search=this.value;updateResearchRows()"><div class="actions"><span class="muted">已勾选 <b id="selection-count">${selected.size}</b></span><button class="small" onclick="batchResearch()">批量调研</button><button class="small primary" onclick="chooseProducts()">加入选品池</button><button class="small" onclick="download('/api/export?kind=research','竞品调研.csv')">导出</button></div></div><div id="research-rows">${researchRows(filteredProducts())}</div><div class="bottom-line"><span>Amazon.it / TikTok Shop / AliExpress / Zooplus / Arcaplanet</span><span>EUR €</span></div></div><div class="notice">报价区分同款、相似款与待核实。销量未公开时显示未知；市场报价和你的目标售价分别展示。内部 SKU 首次需要名称或条码辅助识别。</div>`}
function researchRows(ps){return ps.length?`<div class="table-wrap"><table><thead><tr><th><input aria-label="全选商品" type="checkbox" onchange="selectAll(this.checked)"></th><th>商品 / SKU</th><th>成本 / 库存</th>${platforms.map(p=>`<th>${p}<br><small>价格 · 销量</small></th>`).join('')}<th>操作</th></tr></thead><tbody>${ps.map(p=>`<tr><td><input aria-label="选择 ${esc(p.sku)}" type="checkbox" ${selected.has(p.id)?'checked':''} onchange="selectOne('${p.id}',this.checked)"></td><td>${productCell(p)}${p.researchStatus==='needs_info'?tag('待补资料','orange'):p.researchStatus==='no_quotes'?tag('暂无报价','orange'):''}${p.selected?tag('已选品','green'):''}</td><td><strong>${money(p.cost)}</strong><p>${p.stock==null?'库存待补充':p.stock+' 件'}</p></td>${platforms.map(platform=>{const os=p.offers.filter(o=>o.platform===platform);const o=os.find(o=>o.match==='exact')||os[0];return `<td>${o?`<a href="${esc(safeUrl(o.url))}" target="_blank" rel="noreferrer">${o.currency==='EUR'?money(o.price):esc(o.price+' '+o.currency)}</a><p>${o.sold==null?'销量未知':esc(o.sold+' · '+o.period)}</p>${tag(o.match==='exact'?'同款':o.match==='similar'?'相似款':'待核实',o.match==='exact'?'green':'orange')}`:'<span class="muted">—</span><p>尚无报价</p>'}</td>`}).join('')}<td><button class="text-link" onclick="detail('${p.id}')">查看分析</button><p><button class="text-link" onclick="editProduct('${p.id}')">编辑</button></p></td></tr>`).join('')}</tbody></table></div>`:empty(S.products.length?'没有匹配的商品':'把第一个商品带上线',S.products.length?'换个关键词试试。':'添加 SKU、商品名称和参考图，开始五个平台的对比调研。',`<button class="primary" onclick="editProduct()">＋ 添加 SKU</button>`)}
function updateResearchRows(){$('#research-rows').innerHTML=researchRows(filteredProducts())}
function editProduct(id){const p=id?product(id):{};modal(id?'编辑商品档案':'添加 SKU',`<form id="product-form"><div class="form-grid">${field('sku','仓库 SKU *',p.sku,'text','required maxlength="80"')}<div>${field('ean','EAN / GTIN 条码',p.ean,'text','inputmode="numeric" oninput="showBarcodeHint(this.value)"')}<p class="compact" id="ean-hint">${esc(p.barcodeCheck?.message||'保留前导零；系统会检查条码结构，未收录时可用品牌、型号或包装图辅助。')}</p></div>${field('nameZh','中文名称',p.nameZh)}${field('nameIt','意大利语名称',p.nameIt)}${field('brand','品牌',p.brand)}${field('model','型号 / 货号',p.model)}${field('searchTerms','辅助关键词（中文或意大利语）',p.searchTerms)}${field('supplierUrl','供应商 / 品牌商品链接',p.supplierUrl,'url')}${field('category','品类',p.category)}${field('cost','单件进货成本 €（不含可抵扣税）',p.cost,'number','min="0" step="0.01"')}${field('stock','仓库库存',p.stock,'number','min="0" step="1"')}${field('dimensions','尺寸（如 45 × 35 × 15 cm）',p.dimensions)}${field('weight','重量（注明 g 或 kg）',p.weight)}${field('material','已核实材质',p.material)}<div class="field"><label for="reference-file">包装 / 商品实拍图（也用于识别商品）</label><input id="reference-file" type="file" accept="image/png,image/jpeg,image/webp"></div>${textfield('descriptionZh','中文简介',p.descriptionZh)}${textfield('descriptionIt','意大利语简介',p.descriptionIt)}${textfield('notes','内部备注',p.notes,'full')}<div class="notice full">EAN 查不到时补充品牌、型号或包装图；系统先识别商品，再比较五个平台。未知尺寸、重量、材质请留空。</div>${finishButtons()}</div></form>`);$('#product-form').onsubmit=e=>submitForm(e,async d=>{if(id)d.id=id;const r=await api('products',d);const file=$('#reference-file').files[0];if(file)await uploadReference(r.id,file);$('#dialog').close();await refresh();toast('商品已保存')})}
async function uploadReference(id,file){if(file.size>15*1024*1024)throw Error('参考图最大 15MB');const data=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result.split(',')[1]);r.onerror=no;r.readAsDataURL(file)});await api('reference',{id,data})}
async function chooseProducts(){if(!selected.size)return toast('请先勾选商品');await act('select',{ids:[...selected],selected:true},'已加入选品池，可以安排每天的工作')}
async function batchResearch(){if(!selected.size)return toast('请先勾选商品');let count=0;for(const id of selected){try{await api('jobs',{id,kind:'research'});count++}catch(e){toast(e.message)}}await refresh();toast(`${count} 个调研任务已加入队列，使用本地 Codex`)}
async function startJob(id,kind,extra='',asset=''){const r=await act('jobs',{id,kind,extra,asset},'任务已提交；可在创作工坊查看进度');if(r&&$('#dialog').open)$('#dialog').close()}
function showBarcodeHint(value){
 const code=value.normalize('NFKC').replace(/[\s-]/g,'');let message='未填写条码，可用商品名称、品牌或包装图识别。';
 if(code){if(!/^(?:[0-9]{8}|[0-9]{12}|[0-9]{13}|[0-9]{14})$/.test(code))message='需要 8、12、13 或 14 位数字，请保留前导零。';else{const sum=[...code.slice(0,-1)].reverse().reduce((n,c,i)=>n+Number(c)*(i%2===0?3:1),0);message=(10-sum%10)%10===Number(code.at(-1))?'结构校验通过；不代表网上已收录该商品。':'校验位不匹配，请核对实物上的完整条码。'}}
 const hint=$('#ean-hint');if(hint)hint.textContent=message;
}
function researchDiagnostics(p){
 const check=p.barcodeCheck,identity=p.identity,labels={found:'找到商品页',no_results:'未找到结果',blocked:'访问受限',needs_identity:'待识别商品'};
 const needed=p.researchStatus==='needs_info'||(!p.brand&&!p.nameZh&&!p.nameIt);
 return `<div class="notice"><b>${needed?'先识别商品，再进行比价':'条码与商品识别'}</b><p>${esc(check?.message||'可补充品牌、型号或包装图辅助检索。')}</p>${needed?'<p>请提供品牌＋名称／型号，或上传一张能看清品牌与商品文字的包装图。仅有 EAN 且未被网页收录时，无法可靠判断是哪件商品。</p>':''}${identity?`<p>${esc(identity.reason)}</p>${(identity.sources||[]).map((u,i)=>`<a href="${esc(safeUrl(u))}" target="_blank" rel="noreferrer">身份依据 ${i+1} ↗</a>`).join(' · ')}`:''}<button class="small" onclick="editProduct('${p.id}')">补充品牌、型号或包装图</button></div>${(p.platformResults||[]).length?`<div class="card pad"><h3>本次检索路径</h3>${p.platformResults.map(r=>`<div class="job"><b>${esc(r.platform)}</b> ${tag(labels[r.status]||'待核实',r.status==='found'?'green':'orange')}<p>${esc(r.reason)}</p><p class="compact">尝试的关键词：${esc((r.queries||[]).join(' / ')||'身份资料不足，尚未执行')}</p></div>`).join('')}</div>`:''}`;
}
function pricingTable(p){return `<div class="table-wrap"><table><thead><tr><th>平台</th><th>目标售价（含税）</th><th>单件贡献利润</th><th>利润率</th><th>同款报价</th></tr></thead><tbody>${sellers.map(s=>{const r=p.pricing[s];return `<tr><td>${s}</td><td>${money(r.price)}</td><td>${money(r.profit)}</td><td>${r.margin==null?'—':r.margin+'%'}</td><td>${money(r.market)}</td></tr>`}).join('')}</tbody></table></div>`}
function detail(id){const p=product(id);modal('商品调研与选品建议',researchDiagnostics(p)+`<div class="product-cell" style="margin-bottom:20px">${img(p,true)}<div><h2>${esc(p.nameZh||p.sku)}</h2><p>${esc(p.nameIt||'待翻译')}</p><p class="mono">${esc(p.sku)} · EAN ${esc(p.ean||'待补充')}</p><div class="actions"><button class="primary small" onclick="startJob('${id}','research')">Codex 五平台调研</button><button class="small" onclick="offerDialog('${id}')">＋ 录入报价</button></div></div></div><h3>定价与利润测算</h3>${pricingTable(p)}<p class="compact">利润率按不含税收入计算；扣除进货、物流、平台费、广告及退货预留。未包含固定人工、仓租和所得税，属于贡献利润。费率为可调整假设。</p><div class="notice" style="margin-top:18px"><b>选品建议</b><p>${esc(p.advice||(!p.ean?'建议先补充条码或品牌规格，避免将相似商品误判为同款。':p.cost==null?'请补充成本再评估售价与利润。':'先对照同款市场报价与目标售价，小批量测试；暂无真实销量，不能可靠预测月销量。'))}</p>${(p.researchWarnings||[]).map(w=>`<p>· ${esc(w)}</p>`).join('')}</div><h3>全部来源记录</h3>${p.offers.length?p.offers.map(o=>`<div class="row"><div><b>${esc(o.platform)}</b> ${money(o.price)} ${tag(o.match==='exact'?'同款':o.match==='similar'?'相似款':'待核实')}<p>${esc(o.title)} · ${o.sold==null?'销量未知':esc(o.sold+' / '+o.period)}</p><p class="compact">${esc(new Date(o.checkedAt).toLocaleString())} · ${o.source==='codex_web'?'Codex 网页观测':'手工录入'}</p><a target="_blank" rel="noreferrer" href="${esc(safeUrl(o.url))}">查看来源 ↗</a></div><button class="small" onclick="removeOffer('${id}','${o.id}')">移除</button></div>`).join(''):'<p>尚无记录。发起 Codex 调研或录入平台公开数据。</p>'}`)}
async function removeOffer(id,offerId){if(await act('remove-offer',{id,offerId}))detail(id)}
function offerDialog(id){modal('录入平台报价',`<form id="offer-form"><div class="form-grid">${selectfield('platform','平台',platforms)}${selectfield('match','商品匹配',[['unverified','待核实'],['exact','同款同规格'],['similar','相似商品']])}${field('title','页面商品名称')}${field('price','售价 €','','number','min="0.01" step="0.01"')}${field('sold','公开销量（未知留空）','','number','min="0"')}${field('period','销量口径（近 30 天 / 累计等）')}<div class="full">${field('url','平台商品来源链接 *','','url','required')}</div>${finishButtons()}</div></form>`);$('#offer-form').onsubmit=e=>submitForm(e,async d=>{await api('offer',{...d,id});await refresh();detail(id)})}
function schedule(){const ps=S.products.filter(p=>p.selected),groups={};ps.filter(p=>p.scheduledDate).sort((a,b)=>a.scheduledDate.localeCompare(b.scheduledDate)).forEach(p=>(groups[p.scheduledDate]??=[]).push(p));return head('A LITTLE PROGRESS, EVERY DAY','选品排期','把选中的好产品，变成每天清晰可执行的工作。',`<button onclick="downloadSchedule()">导出排期</button><button class="primary" onclick="scheduleDialog()">＋ 自动排期</button>`)+`<div class="stats">${stat('选品池',ps.length,'调研库中加入的商品')}${stat('等待排期',ps.filter(p=>!p.scheduledDate).length,'按每日产能分配')}${stat('已安排',ps.filter(p=>p.scheduledDate).length,'支持 3 件 / 5 件 / 自定义')}${stat('已完成素材',ps.filter(p=>p.assetsReady).length,'进入上架准备')}</div><div class="card pad"><h2>待安排的商品</h2>${ps.filter(p=>!p.scheduledDate).length?ps.filter(p=>!p.scheduledDate).map(p=>`<div class="row">${productCell(p)}<button class="small" onclick="act('select',{ids:['${p.id}'],selected:false},'已移出选品池')">移出</button></div>`).join(''):'<p>没有等待排期的商品。在调研库勾选商品并加入选品池。</p>'}</div><div class="page-top"><h2>制作日历</h2><span class="muted">点击商品进入创作工坊</span></div>${Object.keys(groups).length?`<div class="calendar">${Object.entries(groups).map(([d,ps])=>`<div class="day"><div class="day-title"><b>${esc(d.slice(5))} ${['周日','周一','周二','周三','周四','周五','周六'][new Date(d+'T12:00:00').getDay()]}</b><span>${ps.length} 件</span></div>${ps.map(p=>`<div class="task" role="button" tabindex="0" onclick="openStudio('${p.id}')" onkeydown="if(event.key==='Enter')openStudio('${p.id}')"><b>${esc(p.nameZh||p.sku)}</b><p>${esc(p.sku)}</p>${tag(p.assetsReady?'素材完成':'待制作',p.assetsReady?'green':'')}<button class="text-link" style="float:right" aria-label="取消排期" onclick="event.stopPropagation();act('unschedule',{id:'${p.id}'},'已取消排期')">×</button></div>`).join('')}</div>`).join('')}</div>`:empty('日历等待你的第一批商品','选择每天 3 件或 5 件，让上新保持稳定节奏。')}`}
function scheduleDialog(){const ps=S.products.filter(p=>p.selected);if(!ps.length)return toast('请先从调研库加入选品');modal('自动安排制作日程',`<form id="schedule-form"><div class="form-grid">${field('start','开始日期',today(),'date','required')}${field('capacity','每天制作数量',3,'number','required min="1" max="50" step="1"')}</div><label class="check"><input name="weekends" type="checkbox">包含周六、周日</label><div style="max-height:280px;overflow:auto;margin:20px 0">${ps.map(p=>`<label class="row"><span>${esc(p.sku)} · ${esc(p.nameZh||p.nameIt)} ${p.scheduledDate?tag(p.scheduledDate):''}</span><input type="checkbox" name="ids" value="${p.id}" ${!p.scheduledDate?'checked':''}></label>`).join('')}</div><p class="compact">已排期商品默认不改动。重新勾选可重排；系统会计入其他商品占用的每日容量。</p>${finishButtons('生成排期')}</form>`);$('#schedule-form').onsubmit=e=>submitForm(e,async d=>{const ids=[...$('#schedule-form').querySelectorAll('[name=ids]:checked')].map(x=>x.value);await api('schedule',{...d,ids,weekends:d.weekends==='on'});$('#dialog').close();await refresh();toast('排期已保存')})}
function openStudio(id){studioId=id;go('studio')}
function studio(){const p=product(studioId)||S.products.find(p=>p.scheduledDate)||S.products[0];if(p)studioId=p.id;return head('ONE PRODUCT. ONE CONSISTENT STORY.','AI 创作工坊','两张九宫格，十八张成品图。统一风格，按平台整理。',`<button onclick="go('settings')">风格与连接</button>`)+`<div class="studio-layout"><div><div class="card"><div class="card-head"><h2>商品队列</h2><span class="pill-number">${S.products.length}</span></div>${S.products.length?S.products.map(x=>`<button class="picker ${p.id===x.id?'active':''}" onclick="studioId='${x.id}';render()">${productCell(x)}<p>${x.scheduledDate?esc(x.scheduledDate)+' · ':''}${x.assetsReady?'素材已生成':'等待制作'}</p></button>`).join(''):'<div class="pad muted">先添加一个 SKU。</div>'}</div><div class="card pad"><h3>制作流程</h3><p class="compact">01 整理事实与实拍图<br>02 生成主图 / 详情九宫格<br>03 按三等分坐标裁剪<br>04 Real-ESRGAN ×4 高清化<br>05 检查并导出平台资料包</p></div></div><div>${p?studioProduct(p):`<div class="card">${empty('为商品建立一致的视觉语言','请先添加商品资料和一张清晰实拍图。',`<button class="primary" onclick="editProduct()">添加商品</button>`)}</div>`}<div class="card pad"><div class="actions" style="justify-content:space-between"><h2>任务中心</h2><button class="small" onclick="refresh()">刷新状态</button></div>${S.jobs.length?S.jobs.slice(0,30).map(jobCard).join(''):'<p style="margin-top:16px">尚无任务。调研与生图都通过本机 Codex 执行。</p>'}</div></div></div>`}
function studioProduct(p){const assets=(p.assets||[]).filter(a=>assetTab==='all'||a.group===assetTab||a.scope.includes(assetTab)),running=S.jobs.some(j=>j.productId===p.id&&['queued','running'].includes(j.status));return `<div class="card pad"><div class="card-head" style="padding:0 0 20px"><div><h2>${esc(p.nameZh||p.sku)}</h2><p>${esc(p.nameIt||p.sku)}</p></div>${tag(p.assetsReady?'素材待检查':'准备制作',p.assetsReady?'green':'')}</div><div class="product-cell">${img(p,true)}<div><p>商品实拍：${p.reference?'已上传':'未上传'}</p><p>名称、尺寸、材质以档案中的已核实资料为准。</p><button class="small" onclick="editProduct('${p.id}')">编辑资料 / 上传实拍</button></div></div><div class="field" style="margin-top:22px"><label for="extra-prompt">本次补充提示词</label><textarea id="extra-prompt" placeholder="例如：统一用意大利现代公寓场景，保持实物颜色和形状。"></textarea></div><div class="actions"><button class="primary" ${running?'disabled':''} onclick="startJob('${p.id}','images',$('#extra-prompt').value)">${running?'任务进行中':'生成两张九宫格 → 18 张高清图'}</button><button onclick="downloadBundle('${p.id}')">导出三平台资料包</button></div><p class="compact">使用本机 ChatGPT 登录的 Codex，不回退到付费生图 API。请求模型：Image Gen 2.5；具体版本尚未验证，以工具实际能力为准。</p></div><div class="card pad"><div class="card-head" style="padding:0 0 20px"><h2>图片素材</h2>${p.assetsReady?`<label class="check"><input type="checkbox" ${p.assetReview?'checked':''} onchange="act('review',{id:'${p.id}',approved:this.checked},'素材检查状态已保存')">我已检查图片，可用于上架</label>`:''}</div><div class="tabs">${[['all','全部'],['通用','通用图片'],['listing','商品图'],['detail','AliExpress 详情']].map(([v,l])=>`<button class="small ${assetTab===v?'active':''}" onclick="assetTab='${v}';render()">${l}</button>`).join('')}</div><div class="nine">${assets.length?assets.map(a=>`<button class="tile" onclick="editAsset('${p.id}','${esc(a.path)}')"><img src="/files/${esc(a.path)}" alt="${esc(a.name)}"><span>${esc(a.scope)}</span></button>`).join(''):['纯白主图','家居场景','核心卖点','工艺细节','尺寸信息','材质特写','使用说明','包装内容','补充展示'].map((l,i)=>`<div class="tile"><b>0${i+1}</b>${l}</div>`).join('')}</div><p class="compact">通用方图用于商品展示；TikTok 竖版营销素材需单独制作。分类为工作建议，上架前仍需核对当前类目规则。点击成品图可提出局部修改。</p></div><div class="card pad"><h3>意大利语上架信息</h3><p><b>${esc(p.nameIt||'意大利语名称待补充')}</b></p><p>${esc(p.descriptionIt||'调研完成后自动翻译已知资料，亦可手动填写。')}</p><div class="row"><span>尺寸</span><span>${esc(p.dimensions||'待核实')}</span></div><div class="row"><span>重量 / 材质</span><span>${esc(p.weight||'待核实')} / ${esc(p.material||'待核实')}</span></div><p class="compact">资料包包含 Amazon、TikTok Shop、AliExpress 三份独立意大利语 Markdown 文档，可复制到平台表单。</p></div>`}
function jobCard(j){
 const labels={queued:'排队中',running:'处理中',completed:'已完成',needs_info:'待补资料',no_results:'暂无报价',failed:'失败',interrupted:'已中断'};
 return `<div class="job"><div class="actions" style="justify-content:space-between"><b>${esc(j.sku)} · ${{research:'五平台调研',images:'九宫格制作',edit:'局部修改'}[j.kind]}</b>${tag(labels[j.status],j.status==='completed'?'green':j.status==='failed'?'red':'orange')}</div><p>${esc(j.message)}</p><div class="actions"><small class="muted">${esc(new Date(j.createdAt).toLocaleString())}</small>${j.folder?`<a class="compact" target="_blank" href="/files/${esc(j.folder.replaceAll('\\','/'))}/events.jsonl">查看日志</a>`:''}${j.edited?`<a target="_blank" href="/files/${esc(j.edited.replaceAll('\\','/'))}">查看修改图 ↗</a><button class="small" onclick="act('adopt-edit',{id:'${j.productId}',jobId:'${j.id}'},'修改图已采用，请重新检查素材')">采用修改图</button>`:''}${['needs_info','no_results'].includes(j.status)?`<button class="small" onclick="editProduct('${j.productId}')">补充商品资料</button>`:''}${['failed','interrupted','needs_info','no_results'].includes(j.status)?`<button class="small" onclick="retryJob('${j.id}')">重试</button>`:''}</div></div>`;
}
function retryJob(id){const j=S.jobs.find(x=>x.id===id);startJob(j.productId,j.kind,j.extra,j.asset)}
function editAsset(id,path){modal('局部二次修改',`<img src="/files/${esc(path)}" style="width:100%;max-height:420px;object-fit:contain" alt="待修改图片"><div class="field"><label for="edit-prompt">描述修改位置与内容</label><textarea id="edit-prompt" placeholder="例如：只将右上角的文字改为…，保留商品、背景和其他布局。"></textarea></div><p>原图保留，修改结果出现在任务中心。</p><button class="primary" onclick="if($('#edit-prompt').value.trim())startJob('${id}','edit',$('#edit-prompt').value,'${esc(path)}');else toast('请描述修改内容')">生成修改版本</button>`)}
function downloadBundle(id){download('/api/bundle?id='+id,product(id).sku+'_平台资料包.zip')}
function uploads(){const ps=S.products.filter(p=>p.assetsReady);return head('READY FOR THE NEXT STEP','上架清单','素材制作完成后，逐个平台完成上架与核对。')+`<div class="stats">${stat('待上传商品',ps.filter(p=>!sellers.every(s=>p.uploaded[s])).length,'至少一个平台尚未完成')}${sellers.map(s=>stat(s,ps.filter(p=>p.uploaded[s]).length,`已完成 / ${ps.length} 个商品`)).join('')}</div><div class="card"><div class="card-head"><h2>平台发布进度</h2>${tag('手动确认 · 不自动发布','green')}</div>${ps.length?`<div class="table-wrap"><table><thead><tr><th>商品</th><th>素材检查</th>${sellers.map(s=>`<th>${s}</th>`).join('')}<th>上架资料</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${productCell(p)}</td><td>${tag(p.assetReview?'已检查':'待检查',p.assetReview?'green':'orange')}</td>${sellers.map(s=>`<td><label class="check"><input type="checkbox" ${p.uploaded[s]?'checked':''} ${p.assetReview?'':'disabled'} onchange="act('upload',{id:'${p.id}',platform:'${s}',done:this.checked},'上架状态已保存')">${p.uploaded[s]?'已上传':'待上传'}</label></td>`).join('')}<td><button class="text-link" onclick="downloadBundle('${p.id}')">下载资料包</button><p><button class="text-link" onclick="openStudio('${p.id}')">检查素材</button></p></td></tr>`).join('')}</tbody></table></div>`:empty('完成制作的商品会出现在这里','在创作工坊生成图片并检查后，即可依次完成三个平台的上传。')}</div>`}
function filteredSales(){return S.sales.filter(s=>(!filters.platform||s.platform===filters.platform)&&(!filters.start||s.date>=filters.start)&&(!filters.end||s.date<=filters.end))}
function sum(rows,k){return rows.reduce((n,s)=>n+(+s[k]||0),0)}
function analytics(){const rows=filteredSales(),revenue=sum(rows,'revenue'),net=revenue-sum(rows,'vatAmount')-sum(rows,'refunds'),profit=sum(rows,'profit');return head('MAKE YOUR NEXT MOVE WITH DATA','经营分析','用实际订单复盘品类、销售与利润，让下一批选品更有依据。',`<button onclick="importDialog('sales')">导入销售 CSV</button><button class="primary" onclick="saleDialog()">＋ 录入销售</button>`)+`<div class="card pad"><div class="form-grid">${selectfield('filterPlatform','平台',[['','全部平台'],...sellers],filters.platform)}${field('filterStart','开始日期',filters.start,'date')}${field('filterEnd','结束日期',filters.end,'date')}<div class="actions"><button class="primary" onclick="applyFilters()">应用筛选</button><button onclick="download('/api/export?kind=sales','销售明细.csv')">导出全部</button><button onclick="exportReport()">老板报告</button></div></div></div><div class="stats">${stat('含税营业额',money(revenue),'实际导入 / 录入的销售数据')}${stat('销售件数',sum(rows,'units'),'筛选区间内的成交数量')}${stat('贡献利润',money(profit),'扣除所填全部可变费用与退款')}${stat('贡献利润率',net>0?(profit/net*100).toFixed(1)+'%':'—','分母：营收 − 销项税 − 退款')}</div><div class="card pad"><div class="card-head" style="padding:0 0 20px"><h2>${chartType==='line'?'每日销售趋势':chartType==='pie'?'品类营收占比':'平台营收与贡献利润'}</h2><div class="tabs" style="margin:0">${[['bar','柱状图'],['line','折线图'],['pie','饼图']].map(([v,l])=>`<button class="small ${chartType===v?'active':''}" onclick="chartType='${v}';render()">${l}</button>`).join('')}</div></div>${rows.length?chart(rows):empty('还没有这个区间的销售数据','录入实际销售和费用后自动生成可视化，不混入演示数字。')}</div><div class="card"><div class="card-head"><h2>销售明细</h2><span class="muted">${rows.length} 条</span></div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>日期</th><th>SKU / 品类</th><th>平台</th><th>件数</th><th>含税营收</th><th>贡献利润</th><th></th></tr></thead><tbody>${rows.sort((a,b)=>b.date.localeCompare(a.date)).map(s=>`<tr><td>${esc(s.date)}</td><td>${esc(s.sku)}<p>${esc(s.category)}</p></td><td>${esc(s.platform)}</td><td>${s.units}</td><td>${money(s.revenue)}</td><td>${money(s.profit)}</td><td><button class="text-link danger" onclick="deleteSale('${s.id}')">删除</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="pad muted">没有销售记录。</div>'}</div><div class="notice">贡献利润未扣固定人工、仓租和所得税。历史销量预测仅在至少 14 个日历天且 5 条记录后显示，使用最近 30 天日均销量外推。</div>${forecast(rows)}`}
function applyFilters(){const f={platform:$('#f-filterPlatform').value,start:$('#f-filterStart').value,end:$('#f-filterEnd').value};if(f.start&&f.end&&f.start>f.end)return toast('开始日期不能晚于结束日期');filters=f;render()}
function chart(rows){const colors=['#7c956d','#cd8c53','#a8b69a','#bca184','#647b59'];const W=920,H=260,left=60,bottom=220,top=22;
 if(chartType==='pie'){const g={};rows.forEach(s=>g[s.category]=(g[s.category]||0)+s.revenue);const total=Object.values(g).reduce((a,b)=>a+b,0);if(!total)return '<p>营收为零，无法计算占比。</p>';let off=0;const entries=Object.entries(g).sort((a,b)=>b[1]-a[1]);const h=Math.max(H,entries.length*27+40);return `<svg class="chart" style="height:${h}px" viewBox="0 0 ${W} ${h}" role="img" aria-label="品类营收占比">${entries.map(([k,v],i)=>{const pct=v/total*100,part=`<circle cx="210" cy="130" r="84" fill="none" stroke="${colors[i%5]}" stroke-width="32" pathLength="100" stroke-dasharray="${pct} ${100-pct}" stroke-dashoffset="${-off}" transform="rotate(-90 210 130)"><title>${esc(k)} ${money(v)} (${pct.toFixed(1)}%)</title></circle><text x="380" y="${35+i*27}" font-size="14" fill="${colors[i%5]}">${esc(k)} · ${money(v)} · ${pct.toFixed(1)}%</text>`;off+=pct;return part}).join('')}<text x="210" y="125" text-anchor="middle" fill="#697165" font-size="13">总营业额</text><text x="210" y="151" text-anchor="middle" font-size="21" fill="#303b32">${money(total)}</text></svg>`}
 const g={};rows.forEach(s=>{const key=chartType==='line'?s.date:s.platform;g[key]??={r:0,p:0};g[key].r+=s.revenue;g[key].p+=s.profit});const entries=Object.entries(g).sort(([a],[b])=>a.localeCompare(b)),vals=entries.flatMap(([,x])=>[x.r,x.p]),max=Math.max(1,...vals),min=Math.min(0,...vals),y=v=>top+(max-v)/(max-min)*(bottom-top),base=y(0),step=(W-left-25)/entries.length;
 let svg=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="营收与贡献利润">`;for(let i=0;i<5;i++){const v=min+(max-min)*i/4;svg+=`<line x1="${left}" y1="${y(v)}" x2="900" y2="${y(v)}" stroke="#e2e5d9"/><text x="50" y="${y(v)+4}" text-anchor="end" font-size="11" fill="#697165">${Math.round(v)}</text>`}
 if(chartType==='bar')entries.forEach(([k,v],i)=>{const x=left+i*step+step*.25,bw=Math.min(55,step*.23);svg+=`<rect x="${x}" y="${y(v.r)}" width="${bw}" height="${Math.max(0,base-y(v.r))}" rx="4" fill="${colors[0]}"><title>${esc(k)} 营收 ${money(v.r)}</title></rect><rect x="${x+bw+7}" y="${Math.min(y(v.p),base)}" width="${bw}" height="${Math.abs(base-y(v.p))}" rx="4" fill="${colors[1]}"><title>贡献利润 ${money(v.p)}</title></rect>`});
 else for(const [key,color] of [['r',colors[0]],['p',colors[1]]]){const pts=entries.map(([,v],i)=>`${left+step*(i+.5)},${y(v[key])}`);svg+=`<polyline points="${pts.join(' ')}" fill="none" stroke="${color}" stroke-width="3"/>`;entries.forEach(([k,v],i)=>svg+=`<circle cx="${left+step*(i+.5)}" cy="${y(v[key])}" r="4" fill="${color}"><title>${esc(k)} ${money(v[key])}</title></circle>`)}
 entries.forEach(([k],i)=>{if(i%Math.max(1,Math.ceil(entries.length/10))===0)svg+=`<text x="${left+step*(i+.5)}" y="247" text-anchor="middle" font-size="12" fill="#697165">${esc(k)}</text>`});return svg+'</svg><div class="legend"><span style="--c:#7c956d">含税营业额</span><span style="--c:#cd8c53">贡献利润</span></div>';
}
function forecast(rows){const by={};rows.forEach(s=>(by[s.sku]??=[]).push(s));const cards=Object.entries(by).map(([sku,rs])=>{const dates=rs.map(s=>s.date).sort(),days=Math.floor((new Date(dates.at(-1))-new Date(dates[0]))/86400000)+1;if(days<14||rs.length<5)return '';const end=new Date(dates.at(-1)),windowRows=rs.filter(s=>(end-new Date(s.date))/86400000<30),span=Math.min(days,30);return `<div class="row"><b>${esc(sku)}</b><span>下 30 天趋势外推：${Math.round(sum(windowRows,'units')/span*30)} 件 ${tag('低置信度','orange')}</span></div>`}).join('');return cards?`<div class="card pad"><h3>销量趋势参考</h3>${cards}<p class="compact">以最后记录日为窗口末日；假设渠道、流量、库存保持不变，无订单日按 0 件计入。促销与缺货会影响可靠性。</p></div>`:''}
function saleDialog(){if(!S.products.length)return toast('请先建立商品档案');modal('录入实际销售与费用',`<form id="sale-form"><div class="form-grid">${selectfield('sku','SKU',S.products.map(p=>[p.sku,p.sku+' · '+(p.nameZh||p.nameIt)]))}${selectfield('platform','平台',sellers)}${field('date','销售日期',today(),'date','required')}${field('units','成交件数',1,'number','min="0" step="1" required')}${[['revenue','含税销售额 €'],['vatAmount','销项税金额 €'],['cogs','本批进货成本 €'],['fees','平台费用 €'],['shipping','本批物流费 €'],['ads','广告费用 €'],['refunds','退款 / 损失 €']].map(([k,l])=>field(k,l,0,'number','min="0" step="0.01" required')).join('')}<div class="notice full">填写该条记录的合计金额，不是单价。退款和销项税请使用一致口径，避免重复扣税。</div>${finishButtons()}</div></form>`);$('#sale-form').onsubmit=e=>submitForm(e,async d=>{await api('sales',d);$('#dialog').close();await refresh();toast('销售记录已保存')})}
function deleteSale(id){modal('删除销售记录',`<p>删除后会重新计算统计结果。这条记录将从本地数据库移除。</p><button class="danger" onclick="act('delete-sale',{id:'${id}'},'已删除记录').then(r=>{if(r)$('#dialog').close()})">确认删除</button>`)}
function settings(){const s=S.settings,c=S.capabilities;return head('YOUR LOCAL OPERATING SYSTEM','连接与设置','本机保存，使用已有的 Codex 登录与九宫格制作流程。',`<button onclick="download('/api/backup','PetOps_备份.zip')">导出完整备份</button>`)+`<div class="grid2"><div class="card pad"><h2>定价假设</h2><p class="compact">以下为初始测算值，不代表平台实际费率，请按业务情况调整。</p><form id="settings-form" onsubmit="saveSettings(event)"><div class="form-grid" style="margin-top:22px">${field('vat','含税售价中的 VAT %',s.vat,'number','min="0" max="80" step="0.1"')}${field('targetMargin','目标贡献利润率 %',s.targetMargin,'number','min="0" max="80" step="0.1"')}${field('shipping','单件物流费 €',s.shipping,'number','min="0" step="0.01"')}${field('adRate','广告预留 / 不含税收入 %',s.adRate,'number','min="0" max="80" step="0.1"')}${field('returnRate','退货预留 / 不含税收入 %',s.returnRate,'number','min="0" max="80" step="0.1"')}${sellers.map((p,i)=>field('fee'+i,p+' 平台费 / 含税售价 %',s.fees[p],'number','min="0" max="60" step="0.1"')).join('')}${textfield('style','全局统一图片风格',s.style,'full')}<div class="full"><button type="submit" class="primary">保存定价与风格</button></div></div></form></div><div><div class="card pad"><h2>本地工作引擎</h2>${[['Codex 程序',c.codex],['九宫格电商法 V1.2',c.skill],['Real-ESRGAN 高清化',c.upscaler],['裁剪与输出脚本',c.finalizer]].map(([l,ok])=>`<div class="row"><span>${l}</span>${tag(ok?'已检测到':'未找到',ok?'green':'red')}</div>`).join('')}<p class="compact">检测到程序不等于已验证生图可用。任务启动时检查 ChatGPT 登录；网络、工具权限和订阅额度以实际结果为准。</p><div class="notice" style="margin-top:18px;margin-bottom:0">${esc(c.modelStatus)}</div></div><div class="card pad"><h2>五平台数据连接</h2>${platforms.map(p=>`<div class="row"><b>${p}</b>${tag('公开网页 / 手动录入')}</div>`).join('')}<p class="compact">尚未接入商家 API。公开网页由 Codex 尝试检索；登录墙、反爬和未公开销量会保留缺失。商家 API 需要各平台授权及接口权限。</p></div><div class="card pad"><h2>数据与隐私</h2><p>数据保存在本机 SQLite。服务仅监听 127.0.0.1，不对局域网开放。调研与作图时，必要的商品资料会发送给 Codex。</p><button class="small" onclick="download('/api/export?kind=products','商品档案.csv')">导出商品档案</button></div></div></div>`}
function saveSettings(e){return submitForm(e,async d=>{d.fees=Object.fromEntries(sellers.map((p,i)=>[p,d['fee'+i]]));await api('settings',d);await refresh();toast('设置已保存，商品目标售价已重算')})}
async function download(url,name){try{const r=await fetch(url);if(!r.ok)throw Error('导出失败');saveBlob(await r.blob(),name)}catch(e){toast(e.message)}}
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function csvEscape(v){let s=String(v??'');if(/^[=+\-@]/.test(s))s=' '+s;return '"'+s.replaceAll('"','""')+'"'}
function downloadSchedule(){const rows=[['日期','SKU','中文名称','意大利语名称','素材状态'],...S.products.filter(p=>p.scheduledDate).sort((a,b)=>a.scheduledDate.localeCompare(b.scheduledDate)).map(p=>[p.scheduledDate,p.sku,p.nameZh,p.nameIt,p.assetsReady?'已生成':'待制作'])];saveBlob(new Blob(['\ufeff'+rows.map(r=>r.map(csvEscape).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'制作排期.csv')}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(c===','&&!quote){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(quote)throw Error('CSV 引号不匹配');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(rows.length<2)throw Error('文件需要表头和至少一行数据');const keys=rows.shift().map(k=>k.trim());if(new Set(keys).size!==keys.length)throw Error('表头重复');return rows.map((r,i)=>{if(r.length!==keys.length)throw Error(`第 ${i+2} 行列数不匹配`);return Object.fromEntries(keys.map((k,j)=>[k,r[j]]))})}
const templates={sales:'id,date,sku,platform,units,revenue,vatAmount,cogs,fees,shipping,ads,refunds',products:'sku,nameZh,nameIt,ean,brand,category,cost,stock,dimensions,weight,material,descriptionZh,descriptionIt'};
function downloadTemplate(kind){saveBlob(new Blob(['\ufeff'+templates[kind]+'\r\n'],{type:'text/csv;charset=utf-8'}),kind+'_模板.csv')}
function importDialog(kind){modal(kind==='sales'?'导入销售数据':'导入仓库商品',`<p>上传 UTF-8 CSV，使用下面的英文列名。商品同 SKU 会更新；销售同 id 会更新，id 留空会新增。</p><div class="notice mono" style="overflow-wrap:anywhere">${templates[kind]}</div><button onclick="downloadTemplate('${kind}')">下载空白模板</button><form id="import-form" style="margin-top:20px"><div class="field"><label for="csv-file">CSV 文件</label><input id="csv-file" type="file" accept=".csv,text/csv" required></div><p>建议先导出备份。最多 5,000 条，校验失败不会写入任何一条。</p>${finishButtons('校验并导入')}</form>`);$('#import-form').onsubmit=e=>submitForm(e,async()=>{const rows=parseCSV(await $('#csv-file').files[0].text());const r=await api('import',{kind,rows});$('#dialog').close();await refresh();toast(`已导入 ${r.count} 条`)})}
function exportReport(){const rows=filteredSales(),doc=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>PetOps 经营报告</title><style>body{font:16px/1.7 -apple-system,BlinkMacSystemFont,"SF Pro Text","PingFang SC","Microsoft YaHei","Segoe UI",sans-serif;background:#fffef9;max-width:1000px;margin:50px auto;color:#303b32;padding:20px}h1{font-size:32px}table{border-collapse:collapse;width:100%}td,th{padding:12px;border-bottom:1px solid #e2e5d9;text-align:left}.chart{width:100%;height:300px}.legend{display:none}@media print{button{display:none}}</style><h1>PetOps Italia · 经营报告</h1><p>${esc(filters.start||'开始')} — ${esc(filters.end||'至今')} · ${esc(filters.platform||'全部平台')}</p><p>营业额 ${money(sum(rows,'revenue'))} ｜ 成交 ${sum(rows,'units')} 件 ｜ 贡献利润 ${money(sum(rows,'profit'))}</p>${rows.length?chart(rows):'<p>无数据</p>'}<table><tr><th>平台</th><th>销售件数</th><th>营业额</th><th>贡献利润</th></tr>${sellers.map(p=>{const rs=rows.filter(s=>s.platform===p);return `<tr><td>${p}</td><td>${sum(rs,'units')}</td><td>${money(sum(rs,'revenue'))}</td><td>${money(sum(rs,'profit'))}</td></tr>`}).join('')}</table><p>来源：本机录入 / 导入的 ${rows.length} 条记录。贡献利润未扣固定人工、仓租和所得税。生成时间：${esc(new Date().toLocaleString())}。</p><button onclick="print()">打印 / 保存 PDF</button></html>`;saveBlob(new Blob([doc],{type:'text/html;charset=utf-8'}),'PetOps_经营报告.html')}
if(navs.some(n=>n[0]===location.hash.slice(1)))view=location.hash.slice(1);
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(navs.some(n=>n[0]===v)&&v!==view){view=v;render()}});
refresh();setInterval(()=>{if(S.jobs.some(j=>['queued','running'].includes(j.status))&&!$('#dialog').open){const editing=document.activeElement?.matches('input,textarea,select');refresh(!editing)}},6000);
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'petops_list_products',title:'读取商品与排期',description:'Read saved product SKUs, schedule dates, and research status from the local workspace.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>{await refresh();return S.products.map(p=>({sku:p.sku,name:p.nameZh,date:p.scheduledDate,research:p.researchedAt||null}))}})}catch(e){console.warn('Optional WebMCP registration unavailable',e)}}
